#!/usr/bin/env python

# Import library
import sys
import json

# Response
result = {'key1':'value_str','key2':12345678,'key3':"value_str"};

print("Content-type: application/json")
print("")
print(json.dumps(result))
