#!/usr/bin/env python

# Import library
import sys
import platform
import json

# Response
info = {'system':platform.system(),'release':platform.release(),'version':platform.version(),'platform':platform.platform()};

print("Content-type: application/json")
print("")
print(json.dumps(info))
