FROM python:slim

# Update linux package manager
RUN apt-get update -y

# Update python package manager
RUN pip install --upgrade pip

# Install linux packages
COPY packages.txt /tmp/packages.txt
RUN xargs apt-get install -y < /tmp/packages.txt

# Install python requirement
COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

# Setting
WORKDIR /app
ENTRYPOINT ["tail"]
CMD ["-f","/dev/null"]
